#  File "/home/eugene/PycharmProjects/python_basic_diploma/utils/print_data.py", line 40, in print_data
#     find_hotels.find_and_show_hotels(message, data)
#   File "/home/eugene/PycharmProjects/python_basic_diploma/utils/find_hotels.py", line 56, in find_and_show_hotels
#     hotels = processing_json.get_hotels.get_hotels(response_hotels.text, data['command'],
#   File "/home/eugene/PycharmProjects/python_basic_diploma/processing_json/get_hotels.py", line 20, in get_hotels
#     for hotel in data['data']['propertySearch']['properties']:
# TypeError: 'NoneType' object is not subscriptable

data = {'errors':
           [{'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}},
            {'message': 'Error occurred in downstream service.',
             'extensions': {'classification': 'DataFetchingException',
                            'event': {'tags': {}, 'name': 'PropertySearchOverFilteredForAppsEvent',
                                      'message': 'Your filter options are not showing a match.', 'level': 'WARN',
                                      'escalation': 'SERVICE', 'spinnername': 'experience-api-lodging-search'},
                            'code': 'DOWNSTREAM_SERVICE_RETURNED_ERROR',
                            'serviceName': 'experience-api-lodging-search'}}], 'data': None}
if 'errors' in data.keys():
    print(data['errors'][0]['message'])

